# Generated by Django 3.0.4 on 2020-04-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
    ]
