# Generated by Django 3.0.4 on 2020-04-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_remove_realtor_listings'),
        ('listings', '0002_remove_listing_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor'),
            preserve_default=False,
        ),
    ]
