# Generated by Django 3.0.4 on 2020-04-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='listings',
        ),
    ]
